# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    strategy: 
      matrix: 
        os: 
         # - windows-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        id: compile
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Binary
          path: ./target/release/billiards
